version: '3.7'

services:
  kb:
    build: .
    container_name: kb
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --proxy-headers
#    ports:
#      - 8000:8000
    expose:
      - 8000
    environment:
      - TZ=America/Vancouver
    networks:
      - ulala

networks:
  ulala:
    external: true